-- Ejecuta esto una sola vez en Supabase > SQL Editor.

create table if not exists public.confirmaciones (
  id bigint generated by default as identity primary key,
  nombre text not null,
  asistira boolean not null,
  numero_asistentes integer not null default 0
    check (numero_asistentes >= 0 and numero_asistentes <= 10),
  mensaje text not null default '',
  created_at timestamptz not null default now()
);

-- La tabla NO queda accesible directamente desde el navegador.
alter table public.confirmaciones enable row level security;

revoke all on table public.confirmaciones from anon, authenticated;
revoke all on sequence public.confirmaciones_id_seq from anon, authenticated;

-- Las funciones de Vercel acceden con SUPABASE_SECRET_KEY,
-- que es exclusivamente de servidor.


-- Evita confirmaciones duplicadas por nombre.
create unique index if not exists confirmaciones_nombre_unico_idx
on public.confirmaciones ((lower(btrim(nombre))));
